---
- name: Déploiement de l'application Symfony
  hosts: web
  become: true

  vars:
    image: "{{ image | default('muhamd/symfony-app:latest') }}"

  tasks:
    - name: Arrêter l'application Docker existante
      shell: docker compose down
      args:
        chdir: /home/mohamed/symfony_project  # <-- adapte ici au chemin réel sur ta machine distante

    - name: Télécharger la dernière image depuis DockerHub
      shell: docker pull {{ image }}

    - name: Redémarrer l'application avec Docker Compose
      shell: docker compose up -d --build
      args:
        chdir: /home/mohamed/symfony_project  # même chemin que ci-dessus
