- name: Déploiement de l'application Symfony
  hosts: web
  become: false
  tasks:
    - name: Stopper l’application existante
      shell: docker compose down
      args:
        chdir: "{{ playbook_dir }}"

    - name: Récupérer la dernière image Docker
      shell: docker pull {{ lookup('env', 'IMAGE') }}

    - name: Redémarrer l'application
      shell: docker compose up -d
      args:
        chdir: "{{ playbook_dir }}"
