- name: Déploiement de l'application Symfony
  hosts: web
  become: true
  tasks:

    - name: Arrêter l'application existante (si elle tourne)
      shell: docker compose down || true
      args:
        chdir: /home/mohamed/app

    - name: Supprimer l'ancien dossier (facultatif si cloné à chaque fois)
      file:
        path: /home/mohamed/app
        state: absent

    - name: Cloner le dépôt GitHub
      git:
        repo: https://github.com/Muhamedch00/Symfony_devops.git
        dest: /home/mohamed/app

    - name: Télécharger la dernière image depuis DockerHub
      shell: docker pull "{{ lookup('env', 'IMAGE') }}"

    - name: Démarrer l'application avec Docker Compose
      shell: docker compose up -d
      args:
        chdir: /home/mohamed/app
