- name: Déploiement de l'application Symfony
  hosts: web
  become: true
  tasks:

    - name: Arrêter l'application existante
      shell: docker compose down
      args:
        chdir: /home/ubuntu/exam_symfony_devops  # chemin Linux sur la VM distante

    - name: Télécharger la dernière image depuis DockerHub
      shell: docker pull muhamd/symfony-app

    - name: Redémarrer l'application avec Docker Compose
      shell: docker compose up -d --build
      args:
        chdir: /home/ubuntu/exam_symfony_devops  # même chemin Linux
